apiVersion: v1
kind: Service
metadata:
  name: developer-social
  labels:
    app: developer-social
spec:
  ports:
    - name: http
      port: 8001
  selector:
    app: developer-social
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: developer-social
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: developer-social
        version: v1
    spec:
      containers:
        - name: social-app
          image: Steven8519/client
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8001
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: developer-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "developer-social"
spec:
  hosts:
    - "*"
  gateways:
    - developer-gateway
  http:
    - match:
        - uri:
            exact: /api/1.0/users
      route:
        - destination:
            host: "developer-social"
            port:
              number: 8001
