apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-social
spec:
  selector:
    matchLabels:
      app: developer-social
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: developer-social
    spec:
      containers:
        - name: developer-social
          image: steven8519/client
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: developer-social
spec:
  selector:
    app: developer-social
  ports:
    - name: http
      port: 80
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: developer-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "developer-social"
spec:
  hosts:
    - "*"
  gateways:
    - developer-gateway
  http:
    - match:
        - uri:
            exact: /api/1.0/users
      route:
        - destination:
            host: "developer-social"
            port:
              number: 8001
