apiVersion: v1
kind: Service
metadata:
  name: devhubsocial-app
  labels:
    app: devhubsocial-app
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: devhubsocial-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devhubsocial-app
spec:
  selector:
    matchLabels:
      app: devhubsocial-app
  replicas: 1
  template:
    metadata:
      labels:
        app: devhubsocial-app
        version: v1
    spec:
      containers:
        - name: devhubsocial-app
          image: steven8519/client
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
