apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: developer-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "devhubsocial.com"
        - "dev.devhubsocial.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: devhubapp
spec:
  hosts:
    - "devhubsocial.com"
  gateways:
    - developer-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: devhubsocial-app
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: developer-social
spec:
  hosts:
    - "*"
  gateways:
    - developer-gateway
  http:
    - match:
        - uri:
            prefix: "/api/1.0/users"
      route:
        - destination:
            port:
              number: 8080
            host: developer-social
