apiVersion: v1
kind: Service
metadata:
  name: developer-social
  labels:
    app: developer-social
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: developer-social
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-social
spec:
  selector:
    matchLabels:
      app: developer-social
  replicas: 1
  template:
    metadata:
      labels:
        app: developer-social
        version: v1
    spec:
      containers:
        - name: devhub-app
          image: steven8519/client
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: developer-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "devhubsocial.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: devhubapp
spec:
  hosts:
    - "devhubsocial.com"
  gateways:
    - developer-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: developer-social
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: developer-social
spec:
  hosts:
    - "*"
  gateways:
    - developer-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8001
            host: developer-social
