apiVersion: v1
kind: Service
metadata:
  name: devhubsocial-app
  labels:
    app: devhubsocial-app
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: devhubsocial-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devhubsocial-app
spec:
  selector:
    matchLabels:
      app: devhubsocial-app
  replicas: 1
  template:
    metadata:
      labels:
        app: devhubsocial-app
        version: v1
    spec:
      containers:
        - name: devhub-app
          image: steven8519/client
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: devhubsocial-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "devhubsocial.com"
        - "devhubsocial.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: devhubsocial
spec:
  hosts:
    - "devhubsocial.com"
  gateways:
    - devhub-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: devhubsocial-app
            port:
              number: 80
